# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and test openaire-cris-validator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout the OpenAIRE Guidelines for CRIS Managers repo
      run: git clone --branch=master https://github.com/openaire/guidelines-cris-managers.git ../guidelines-cris-managers
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn package -Dmaven.javadoc.skip=true -B -V
    - name: Run the validator on the example files
      run: java -jar target/openaire-cris-validator-*-jar-with-dependencies.jar file:samples/
